### ISSUE TITLE
Kingdom Hearts : Chain of Memories crash during introduction

### ISSUE THREAD

**Issue by schmurtzm** [libretro/gpsp#183] opened 2023-01-07 19:17 UTC
Kingdom Hearts : Chain of Memories crash during introduction

https://user-images.githubusercontent.com/7110113/211166985-853ba687-b133-4c19-9d92-03975c5b5a46.mp4

**Plateform** : armv7 +neon , same behavior on x86

dynarec ON + interframe blending OFF -> crash
dynarec ON + interframe blending ON -> no crash
dynarec OFF + interframe blending OFF -> no crash
dynarec OFF + interframe blending ON  -> no crash

Tested with last gPSP commit : 90170e33894ac8e3598a5660da62a18884d795f4 5 jan 2023

**Comment by andymcca** [comment] 2023-01-07 19:51
Same with or without Dynarec?

**Comment by schmurtzm** [comment] 2023-01-07 21:21
Description updated.

**Comment by andymcca** [comment] 2023-03-19 13:53
Did a quick bit of research on this.

In the original gpSP and forks (for the PSP) this problem existed and could be worked around by taking a Save State at the time of the crash, and then resuming.  Not sure if this will work in lr-gpsp as Savestates were overhauled last year.

According to some forum postings I've seen, this issue was apparently fixed in later forks such as Kai and TempGBA4PSP.  I'd be interested to know if this is still an issue in ReGBA for example.

**Comment by andymcca** [comment] 2023-03-20 20:46
Just done a PR to fix this on ARM32 at least.

**Comment by andymcca** [comment] 2023-03-20 22:00
@schmurtzm I thought I had a proper fix for this but have now found out it doesn't fix it.  But there is a workaround -

When the crash happens, go to the RetroArch menu and restart the ROM (or close the ROM and load it again straight away).  On my platform the intro then runs through as normal?

**Comment by davidgfnet** [comment] 2023-04-09 13:55
I think I might have found the underlying issue. And it fixes a bunch of other games. Due to the way I run the tests I do not tend to "observe" any issues that freeze a game yet do not cause a an emulator crash.
To mitigate that I ran all games and recorded their output for 2.5 minutes. I will upload this later so that others can peek and see any games that do not work (or at least, that do not even get in-game).
Back to the issue, after looking at the IRQ/DMA epiloge issue for ARM, and realizing there's a few bugs hidden down there, I read GBATEK a bit more. I realized there's a bunch of other bugs related to IRQs and the registers that control it. In particular there's an issue with some masking registers that do not re-trigger IRQs when the mask is cleared. This is a double issue: the fact that pending IRQs are not triggered in some paths (due to its complexity) and that these pending IRQs are not re-checked at later times (which would be wrong yet better than nothing!).
Anyway I will send some more commits later fixing some of this, and hopefully improving the accuracy of the IRQ paths.
Thanks for reporting this! It does help a lot when people point to bugs in a way that I can reproduce it (ie. adding videos, screenshots, proper explanations, savestates/savefiles, etc).

**Comment by andymcca** [comment] 2023-04-09 15:26
That's great news David, pleased to hear you've potentially found a proper fix.  Look forward to your commits so that I can build and test! ☺️

**Comment by davidgfnet** [comment] 2023-04-10 11:08
Hey @andymcca @schmurtzm mind testing this again and see whether it fixes the issue? It does for me on x86/arm so I assume this could be the issue. Of course it is still possible that we just nudge the timing a bit causing it to work but the underlying issue is still there :)

**Comment by andymcca** [comment] 2023-04-10 12:17
Initial testing looks good!  I have tried 3 runs through the intro cut-scene and no crash yet.  

We are out this afternoon so tonight I will try as I was doing before i.e. 10 cold start run throughs of the cut-scene.  If no crashes then I think we can safely say this has fixed it 👍

**Comment by andymcca** [comment] 2023-04-10 18:20
@davidgfnet - 10 cold start run completed - not a single crash ☺️ 

Think this one can be closed and marked as completed!

**Closed** 2023-04-10 19:18 UTC
