### ISSUE TITLE
Dynarec Crashes on "New" 3DS 

### ISSUE THREAD

**Issue by Haze3ds** [libretro/gpsp#36] opened 2017-03-25 00:31 UTC
Having the dynarec enabled on a "New" 3DS causes the game to crash after a random amount of time(short). Using Jet Set Radio(E) it's a matter of seconds. I believe the old 3DS is unaffected. 

I can replicated in builds 1.3.3 and 1.50 stable and everybuild in between suffers the issue.

**Comment by TriforceOfPwnage** [comment] 2019-05-10 20:43
I can confirm this still happens on latest build. Also even 1.3.2 has this issue too

**Comment by flowlee** [comment] 2019-08-09 00:29
I can confirm this is still an issue with the latest nightlies from August 2019.

**Comment by davidgfnet** [comment] 2021-09-02 23:10
Can someone recheck this?   @justinweiss provided a fix for this and seems to work in pcsx_rearmed, Im gonna assume this works here too unless someone rechecks and says it does not :)

**Comment by justinweiss** [comment] 2021-09-03 01:24
When I looked into it, it seemed to have the same symptoms as the pcsx_rearmed crash. I haven't heard of any of these kind of crashes since the fix.

**Closed** 2021-09-05 15:30 UTC
