### ISSUE TITLE
Yggdra Union cannot perform battery save

### ISSUE THREAD

**Issue by cbrumbau** [libretro/gpsp#189] opened 2023-02-11 04:32 UTC
When you try to perform an in game save in Yggdra Union, you get the error FAILED! Save failed!

Testing was done on gpSP v0.91 2fcbdc1

**Comment by andymcca** [comment] 2023-04-10 18:02
Hi,
Please can you provide a save state at the point of creating the first Save?  Seems like you have to play through a New Game for quite a bit before getting to this point.  A save state will help massively in being able to diagnose this issue.  

Thanks!
Andy

**Comment by andymcca** [comment] 2023-05-03 17:13
Hi,
I've confirmed this issue on the latest commit - as a workaround I believe you can use the gbata utility to patch this ROM to use SRAM for saving instead of EEPROM.  

This fork of gpsp will need to have the 'savetype' option for game_config.txt / gba_over.h implemented, which I believe exists in TempGBA.  Once this is done, an game-specific entry should solve the problem.

Thanks
Andy

**Comment by andymcca** [comment] 2023-08-02 23:17
I've just done a PR to implement save type overrides.  I will test with this game to see if an override entry will resolve it.

**Comment by andymcca** [comment] 2023-08-05 12:10
@cbrumbau My PR #220 fixes this game by manually setting the save type to eeprom 8k.  But need to wait for this to be checked and reviewed first before it can be merged with the main gpsp codebase.

**Comment by davidgfnet** [comment] 2023-10-02 17:38
We fixed this one right Andy? It was an issue with the memory mappings (since the ROM is 32MB in size and takes all the address space).

**Closed by davidgfnet** 2023-10-02 17:38 UTC

**Comment by andymcca** [comment] 2023-10-02 18:10
@davidgfnet Yes correct, fixed now, exactly the issue you state and you corrected it in commit 6e59ca6!
