### ISSUE TITLE
[VITA] Golden Sun issues

### ISSUE THREAD

**Issue by Zarke669** [libretro/gpsp#166] opened 2021-11-30 02:40 UTC
graphical error in game intro and normal attack sound seems too low.
![image](https://user-images.githubusercontent.com/58910688/143976012-62ab7dd8-7191-4c46-b0d9-b26fb636871e.jpg)

**Comment by Zarke669** [comment] 2021-12-01 04:51
![Uploading image.jpg…]()

**Comment by Zarke669** [comment] 2021-12-01 05:04
![Uploading 4AAFD93E-FF59-4D9E-AD71-849A6D074545.jpeg…]()

**Comment by Zarke669** [comment] 2021-12-01 05:05
![Uploading 7702D87C-FDE1-4ED2-9A36-92983B9E0D33.jpeg…](). :(

**Comment by Zarke669** [comment] 2021-12-01 08:55
![Uploading DB989C5B-E375-4ED8-8DA1-20B73731006F.jpeg…]()

**Comment by Zarke669** [comment] 2021-12-01 22:59
![Uploading 4CCD6DC9-0688-43F0-978C-B073B1B9A315.jpeg…]()

**Comment by Zarke669** [comment] 2021-12-01 22:59
![97E193BB-377F-483B-954D-B2B9AA160D0C](https://user-images.githubusercontent.com/58910688/144327888-f5927612-214f-4302-b985-682505ed131b.jpeg)

**Comment by Zarke669** [comment] 2021-12-01 23:00
![Uploading D6B75DD0-7297-42D5-BB1E-D0A99A6E6401.png…]()

**Comment by Zarke669** [comment] 2021-12-01 23:01
![Uploading image.jpg…]()

**Comment by Zarke669** [comment] 2021-12-01 23:03
![Uploading D446B25C-1F1E-4975-86D3-EAB22E29F674.jpeg…]()

**Comment by Zarke669** [comment] 2021-12-02 02:13
![Uploading 8E156F22-CB35-4ED5-AC43-E894A8A8E6FD.jpeg…]()

**Comment by Zarke669** [comment] 2021-12-02 02:13
![Uploading D6505EF5-4807-4052-9DF2-FE13230A2685.jpeg…]()

**Comment by Sin2FX** [comment] 2022-01-02 15:04
On PS2 this game crashes and feeze after some minutes playing it

**Comment by Darkstalix** [comment] 2022-12-29 20:58
I see this issue was opened last year so i dont think there might be a fix in the future but anyway why not right them here
The only graphical glitch is the one OP mentioned only, the sun glare
There are a lot of sound issues and it feels like they happen because too many sounds are supposed to happen at the same time on impact and its like a sound channel missing or smth. 
-Normal Attack sound is missing or waay too low
-Odyssey/Liquifier/Megiddo/summons have a lot of slowdowns

**Comment by DrUm78** [comment] 2023-04-21 15:17
Hardware: FunKey S device (armv7 32-bit) with 64MB RAM
Software: [PicoArch frontend](https://git.crowdedwood.com/picoarch/)
OS: Custom Linux 4.14.14
Commit: https://github.com/libretro/gpsp/commit/2d28451f6cb74eed09203b4b3a2da3549dd27cc9

Same issues happen on classic_armv7_a7 fyi.

**Comment by andymcca** [comment] 2023-05-20 16:41
Sound issue is actually the noise channel missing - I did a couple of PRs based on the TempGBA code to try and fix but these aren't quite right either, so have agreed with David to close these whilst he takes time to develop a proper fix.  If you are impatient and happy to mess about with your own build, you can try applying the code in PR #203 which you should find brings the battle sounds back (albeit definitely not 100% accurate!).

The slowdowns are likely due to self-modifying code hammering the recompiler - have also been chatting with David about this recently and he has some ideas on implementing some measures to handle this better (same as TempGBA/ReGBA).

**Comment by andymcca** [comment] 2023-06-18 18:49
Graphics issues on intro are down to broken OBJ transparency implementation.  Long explanation in issue #74.

**Comment by andymcca** [comment] 2023-07-16 11:01
Attack sound is fixed in the most recent commit 1d972ec !

**Comment by DrUm78** [comment] 2023-07-16 14:00
I confirmed that it's now fixed in GS 1 & 2, thanks! 👍

**Comment by davidgfnet** [comment] 2023-08-27 08:13
As mentioned in https://github.com/libretro/gpsp/issues/74 the GFX effects are fixed. The sound (noise channel) is also fixed, even tho there's still a few small bugs there which I will fix in an upcoming PR.
Let's close this. Feel free to open an issue if any other issue is still present.

**Closed by davidgfnet** 2023-08-27 08:13 UTC

**Comment by DrUm78** [comment] 2023-08-27 08:42
The graphical glitch seems to be fixed now indeed, thanks! 🙏

**Comment by Darkstalix** [comment] 2023-08-28 19:22
Graphical and sound issues fixed ty so much
please try if its possible for Boreas summon screen gets black and you can only see the battle log below

**Comment by andymcca** [comment] 2023-09-17 07:42
@Darkstalix please provide a save file or better still a save state so we can try and reproduce the black screen issue

**Comment by Darkstalix** [comment] 2023-09-17 17:25
> @Darkstalix please provide a save file or better still a save state so we can try and reproduce the black screen issue

Hey thanks for attempting this it happens to both golden sun 1 and 2
Both my roms and saves are from my original carts from EU region( i cant recall if there was a region compatibility for saves)
![1](https://github.com/libretro/gpsp/assets/121641215/4f1eaf6e-438e-4810-9724-33941563aeae)
[Golden sun states and saves.zip](https://github.com/libretro/gpsp/files/12643338/Golden.sun.states.and.saves.zip)

**Comment by andymcca** [comment] 2023-09-17 19:06
@davidgfnet may be worth reopening this or moving to a new issue.  From the above, this is on the latest commit. albeit a very specific point in the game - I'm happy to do some testing with the previous renderer etc to see if this has always been the case.

**Comment by Darkstalix** [comment] 2023-09-17 19:38
its not a specific point in game in terms of story place etc. just using the Boreas summon this happens, you get a black screen till the end of the summon cutscene

**Comment by andymcca** [comment] 2023-09-17 21:17
@Darkstalix got it, thanks for the clarification.

**Comment by davidgfnet** [comment] 2023-09-19 18:38
You are right sir, it seems there's a bug in the windowing horizontal limit logic. I fixed this in my fork (https://github.com/davidgfnet/gpsp/commit/1d46986e928c927ef42bbe2a20f10ed21b1bd2c5). I will merge this in the upcoming days, stay tuned.

**Comment by Burlz10** [comment] 2023-09-24 02:58
Hi, I started a new ticket for this without realizing this issue was already being covered. If additional save states or save files are needed for testing please let me know. In addition I noticed a graphical glitch in which background elements end up in the foreground. Should this become its own ticket? Thanks. 
![IMG_3193](https://github.com/libretro/gpsp/assets/145821419/900f83ed-6d30-4aee-b3b1-069df717d161)
![IMG_3192](https://github.com/libretro/gpsp/assets/145821419/93b70225-bec6-4a73-8930-b740d1e69268)

**Comment by andymcca** [comment] 2023-09-24 06:50
Please start a new issue for the carpet glitch as this is separate to the above.

**Comment by Burlz10** [comment] 2023-09-24 07:01
Thank you. New ticket was started
