### ISSUE TITLE
[Android] Can't delete gPSP core in RetroArch

### ISSUE THREAD

**Issue by DJM75** [libretro/gpsp#68] opened 2020-04-19 09:43 UTC
When you load the gPSP core and then click on "Information" you can't see there the "Core Information" section from which you can delete the core (just like you can do with every other core in RetroArch...).

**Comment by hizzlekizzle** [comment] 2020-04-19 15:01
Hmm, do you have the core info file for it? https://github.com/libretro/libretro-super/blob/master/dist/info/gpsp_libretro.info

Is it failing to load the core at all, perhaps?

**Comment by DJM75** [comment] 2020-04-23 15:42
I figured out the problem, I can't delete the core because RetroArch can't even load it. I enabled file log in RetroArch and I noticed that when I try to load this core I get this error:

"Error(s): dlopen failed: /data/data/com.retroarch/cores/gpsp_libretro_android.so: has text relocations"

Is there a way to fix it?

**Comment by DJM75** [comment] 2020-04-23 15:43
> Is it failing to load the core at all, perhaps?

Yes, I figured out the problem, I can't delete the core because RetroArch can't even load it. I enabled file log in RetroArch and I noticed that when I try to load this core I get this error:

"Error(s): dlopen failed: /data/data/com.retroarch/cores/gpsp_libretro_android.so: has text relocations"

What's that error? Is there a way to fix it?

**Comment by hizzlekizzle** [comment] 2020-04-23 16:27
Hmm, i think that means it doesn't like the dynarec. i don't think there's anything to be done about it, short of deleting the app data.

**Comment by davidgfnet** [comment] 2021-05-05 19:38
This is a duplicate of #41 
Can you please comment there whether this is still an issue? Thanks!

**Closed by davidgfnet** 2021-05-05 19:38 UTC
