### ISSUE TITLE
[ARM 32-Bit] Colin McRae Rally crash after menu (works in gpSP 0.9 PSP)

### ISSUE THREAD

**Issue by andymcca** [libretro/gpsp#179] opened 2023-01-03 09:56 UTC
This game crashes at a certain point in the menu when running on an ARM platform in Dynarec mode.  However this issue was fixed in gpSP 0.9 (see Exophase release notes) - confirmed this by running standalone gpSP 0.9 on PPSSPP and loading the game (it worked through to in-game) and also on lr-gpsp in Windows.

I suspect this is due to the implementation of arm_stub.S - it looks as if some jump conditions are missing in the execute cspr / spsr functions which are present in mips_stub.S, which are probably the fix that Exophase refers to in his release notes.  However I'm not very familiar with ARM/MIPS assembler,   Can anyone help????

**Comment by andymcca** [comment] 2023-01-04 10:54
Update - I tried making a change to arm_stub.S in my own repo for gpSP standalone, but it didn't fix the issue.

I think it would be worth porting @davidgfnet's ARM64 Dynarec to ARM32, thus replacing the existing files - I'm happy to start looking at this but not likely to progress it anytime soon due to other commitments, especially as now back at work after Christmas!!

**Comment by davidgfnet** [comment] 2023-01-05 20:27
Hey there!
The reason why the arm32 dynarec is so different to the others, it's cause it's essentially an arm2arm translator, whereas mips, arm64 or x86 are actually doing translation. That makes arm32 faster (compared to the other dynarecs).
I debugged the issue and it's what you mention: spsr-restore doesnt work as intended on usermode (cpu_mode=0). This is something that games shouldnt do (since it is undefined according to the arm manual), however a couple of them do.
I fixed this in my fork, I will merge this in a minute. Thanks for reporting!

**Comment by davidgfnet** [comment] 2023-01-05 21:27
This is fixed by https://github.com/libretro/gpsp/commit/90170e33894ac8e3598a5660da62a18884d795f4

**Closed by davidgfnet** 2023-01-05 21:27 UTC

**Comment by andymcca** [comment] 2023-01-05 23:13
> This is fixed by [90170e3](https://github.com/libretro/gpsp/commit/90170e33894ac8e3598a5660da62a18884d795f4)

Ahhh that's great David thank you for all your great work on this emulator and also for taking the time to come back and fix this issue.  As mentioned I run lr-gpSP and gpSP standalone (my fork from the notaz version) on Leapster Explorer and LeapsterGS devices, and have been messing with trying to fix certain things where I can (my C and assembler knowledge isn't great but that's how you learn right? :-)) .  

These devices are pretty old now, the Explorer in particular runs an armv5te 32-bit CPU, but both lr-gpSP and gpSP run very well, so it's interesting to me to investigate and try to help tie up the last few mainstream games that have compatibility issues.

**Comment by schmurtzm** [comment] 2023-01-07 19:19
Tested with last gPSP commit : 90170e33894ac8e3598a5660da62a18884d795f4 5 jan 2023 , work great. Thanks @davidgfnet !
