### ISSUE TITLE
gpsp segfaults on pokemon *

### ISSUE THREAD

**Issue by BlackLotus** [libretro/gpsp#5] opened 2015-01-05 01:32 UTC
If you try to load pokemon emerald retroarch segfaults (didn't analyze any coredump yet)
If you first load pokemon emerald with vbam press f1 and then load (you can even select the gpsp entry from history) it suddenly works.

**Comment by vanfanel** [comment] 2015-01-05 01:58
I can confirm it happens here, too. 
Tested on X86 with no JIT where it works with no problems.
So: it happens on ARM (Rpi, Cubie2) but not on X86.

**Comment by BlackLotus** [comment] 2015-01-05 03:15
Compiled it with
 HAVE_DYNAREC := 0
and
 CFLAGS += -DARM -DARM_ARCH
Didn't help. (I removed -DARM_MEMORY_DYNAREC)

**Comment by dankcushions** [comment] 2015-07-20 12:09
I'm not sure if this is the same issue, but I get segfaults on the pokemon sapphire with an RPI 2 (ARM), but if I run the same in the non-libretro version of GPSP (https://github.com/libretro/gpsp), the same game works.

I think these issues may be resolved by a merge of the latest changes in the master version of GPSP. Eg, there appear to be changes to the arm folder in the master, that aren't in this version.

**Comment by NHellFire** [comment] 2017-04-05 22:44
Also crashes on my Vita with RetroArch nightly 2017-04-04. Doesn't crash in [gpsp kai v3.4 test 4 build 225](http://wololo.net/talk/viewtopic.php?f=47&t=45844)
Core dump attached
[psp2core-1491426428-0x0003572e71-gpsp_libretro.self.psp2dmp.gz](https://github.com/libretro/gpsp/files/900973/psp2core-1491426428-0x0003572e71-gpsp_libretro.self.psp2dmp.gz)

**Comment by andymcca** [comment] 2023-07-31 16:32
Just tested using the most recent commit and Pokemon Emerald works without issue.  Given that this worked ok in the gpsp standalone versions, I suspect this issue got fixed when the timer bug was discovered/resolved in commit 413157dedd92aeda6850e92c73d5b3b4809bcb73.  @davidgfnet this issue can be closed now.

**Comment by davidgfnet** [comment] 2023-08-02 21:34
Yeah we fixed a bunch of segfaults in some games. I would assume this is fixed.
Please reopen if it is not. gpsp has changed a lot since 2017!

**Closed by davidgfnet** 2023-08-02 21:34 UTC
