### ISSUE TITLE
64-bit integer division causes games to crash

### ISSUE THREAD

**Issue by exelotl** [libretro/gpsp#225] opened 2023-09-21 17:02 UTC
Whenever a 64-bit integer division occurs (signed or unsigned), my game hangs.

I guess the underlying cause isn't specific to division, since division is done in software on the GBA. Maybe there's some instruction within the 64-bit division routine in libgcc that's not emulated properly?

Here's an example:

```c
// Based on obj_demo.c by cearn

#include <string.h>
#include <tonc.h>
#include "metr.h"

OBJ_ATTR obj_buffer[128];

void obj_test() {
  
  uint x = 96, y = 32;
  u32 tid = 0, pb = 0;		// tile id, pal-bank
  
  OBJ_ATTR *metr = &obj_buffer[0];
  obj_set_attr(metr, ATTR0_SQUARE, ATTR1_SIZE_64, ATTR2_PALBANK(pb) | tid);
  
  while (1) {
    vid_vsync();
    key_poll();
    
    // You can move with the arrow keys:
    x += 2 * key_tri_horz();
    y += 2 * key_tri_vert();
    
    if (key_hit(KEY_START)) {
      
      // Pressing START should *scale* the X coordinate by a small amount.
      // But on gpSP it locks up the game instead.
      
      x = (x * ((u64) 61000)) / ((u64) 59737);
    }
    
    metr->attr2 = ATTR2_BUILD(tid, pb, 0);
    obj_set_pos(metr, x, y);
    
    oam_copy(oam_mem, obj_buffer, 1);  // Copy into real OAM.
  }
}

int main() {
  memcpy(&tile_mem[4][0], metrTiles, metrTilesLen);
  memcpy(pal_obj_mem, metrPal, metrPalLen);
  
  oam_init(obj_buffer, 128);
  REG_DISPCNT = DCNT_OBJ | DCNT_OBJ_1D;
  
  obj_test();
  
  return 0;
}
```

Here's the project (build files included, can be recompiled with devkitARM): [gpsp_bug.zip](https://github.com/libretro/gpsp/files/12689168/gpsp_bug.zip)

**Comment by davidgfnet** [comment] 2023-09-22 21:35
Hey there, just adding this to not forget about what the issue is.
The issue is with the STM instructions. In particular, the divmod code (likely handwritten asm) for the armv4 uses a "push {sp, lr}" instruction, which in gpsp is incorrectly emulated. The new SP value is written to memory, as opposed to the old value. According to GBATEK and other emus, there's a few corner cases for this instruction which we do not handle.
Thanks for the report. This is a high quality report and helps a lot :)

**Comment by davidgfnet** [comment] 2023-11-08 00:22
Allright! I fixed this issue on the interpreter (in my fork) and seems to properly run the attached demo.
I will rewrite some of the dynarec code to bring the fix to all platforms.
Thanks again for the report! It seems many homebrew run into this due to some library code that devkitpro's toolchain ships.

**Comment by davidgfnet** [comment] 2023-11-22 18:50
Added a few fixes. Doesnt fix the issue a 100% yet (only ARM mode for now), and the dynarec doesn't correctly emulate the CPU behavriou, but it behaves like mGBA does, so it should work.
Lemme know if it still fails in some other funny way :) 
I will keep this open until I fix the other instructions and some other funny corner cases. Thanks!

**Comment by davidgfnet** [comment] 2023-12-20 18:16
Not all LDM/STM instructions have been fixed, however I wrote a few tests to track this (at https://github.com/davidgfnet/test-rom-suite/). I'm gonna close this since the reported issue is indeed fixed, and perhaps file an issue to ensure we fix other corner cases. Thanks for the report! Fixed a few other homebrews

**Closed by davidgfnet** 2023-12-20 18:16 UTC
