### ISSUE TITLE
[n3ds] Crashlogs, dunno if they'll ever help but there you go

### ISSUE THREAD

**Issue by Clydefrosch22** [libretro/gpsp#38] opened 2017-08-26 09:30 UTC
So I've been playing a lot of gpsp these past two weeks and I got loads of crashes, as is usual for gpsp since forever.
I dunno if anyone will ever fix dynarec, or if these dumps are of any help when that day comes, but here you go.
If you know a better upload service, i'm all ears.

http://s000.tinyupload.com/index.php?file_id=94666941028931534677

these are from the 1.6.7 version

**Comment by Clydefrosch22** [comment] 2018-05-04 17:45
Not surprising, I don't think anyone goes near the dynarec issue, though I can't say for sure if its lack of interest or because the dynarec is not open source enough for people to try and fix it.
It's just a real shame considering the n3ds is very much perfectly capable of pulling full speed no stuttering all nice extra options gba emulation off.
And mgba would rather be stuck at wonky 40-55 frames forever in the name of accuracy (which, considering all the graphic artifacts, it also doesn't even come close too)

**Comment by justinweiss** [comment] 2020-03-27 00:18
Ingame crashes should now be resolved, if you'd like to give it another try!

**Comment by Clydefrosch22** [comment] 2020-03-27 00:21
yes, i heard and there certainly are fewer crashes than before. still managed to get a few since updating to 1.8.5 though

**Comment by justinweiss** [comment] 2020-03-27 01:04
In-game or when changing games? I've seen some when switching from one game to another, but haven't hit any in-game crashes since the fix.

**Comment by Clydefrosch22** [comment] 2020-03-27 10:17
Certainly some during changing, some a short while after changing a game, once just after starting up and letting kirby nightmare in dreamland sit idly on the title screen for a while

**Comment by davidgfnet** [comment] 2023-06-07 19:53
I will close this since many games have been fixed in the recent months. If there's some specific crashes that you wanna see fixed, feel free to open a new Issue and post a savestate, video/screenshot/photo, details on how to reproduce, etc.
Do similar crashes happen with other emulators in Retroarch? We shouldnt rule out bugs on the frontend itself, since n3ds is a relatively small platform.
Thanks!

**Closed by davidgfnet** 2023-06-07 19:53 UTC
